const $=s=>document.querySelector(s);
function query(){return new URLSearchParams({crowd:$("#crowd").value,smoke:$("#smoke").value,corridor_capacity:$("#capacity").value,block_b:$("#blockB").checked?"1":"0"})}
function render(d){
 $("#state").innerHTML=Object.entries(d.scenario.initial_state).map(([k,v])=>'<div class="finding"><span>'+k.replaceAll("_"," ")+'</span><b>'+Number(v).toFixed(1)+'</b></div>').join("");
 $("#futureCount").textContent=d.futures.length;$("#robustCount").textContent=d.robust.length;$("#bestScore").textContent=d.robust.length?d.robust[0].score.toFixed(1):"—";$("#latticeState").textContent="EXPLORED · H="+((d.uncertainty&&d.uncertainty.risk_entropy)||0).toFixed(2);
 $("#branches").innerHTML=d.future_tree.map((f,i)=>'<div class="branch"><b>BRANCH '+String(i+1).padStart(2,"0")+'</b><small>'+JSON.stringify(f.policy)+'</small><small>objective <strong>'+f.score.toFixed(1)+'</strong> · <span class="'+(f.valid?"valid":"invalid")+'">'+(f.valid?"GUARDIAN PASS":"GUARDIAN REJECT")+'</span></small></div>').join("");
 $("#chaos").innerHTML=d.robust.slice(0,4).map(x=>'<div class="finding"><span>'+JSON.stringify(x.policy)+'<br><small>perturbation '+JSON.stringify(x.worst_perturbation)+'</small></span><strong>'+x.worst_case_score.toFixed(1)+'</strong></div>').join("");
 const causal=document.querySelector("#causal"); if(causal) causal.innerHTML=d.causal_graph.edges.map(e=>"<div class=\"branch\"><b>"+e.cause+"</b><small>→ "+e.effect+"</small><small>strength "+e.strength.toFixed(2)+"</small></div>").join(""); const vals=d.futures.map(x=>x.score),max=Math.max(...vals),min=Math.min(...vals);$("#bars").innerHTML=vals.map(v=>'<div class="bar" style="height:'+(30+70*(max-v)/Math.max(max-min,1))+'%"><span>'+v.toFixed(0)+'</span></div>').join("");
 $("#benchmark").innerHTML=d.benchmark.map(b=>'<div class="finding"><span>'+b.method+'<br><small>'+b.note+'</small></span><strong>'+b.energy.toFixed(2)+' · '+b.runtime_ms.toFixed(2)+'ms</strong></div>').join("");
 const q=d.benchmark.find(b=>b.method==="qaoa-statevector-simulator");$("#qaoaMeta").textContent=q?"p=1 · expected energy "+q.expected_energy.toFixed(2)+" · probability "+(q.probability*100).toFixed(1)+"%":"";
 const w=d.robust[0];$("#guardian").innerHTML=w?'PASS · '+JSON.stringify(w.policy)+'<div style="font-size:11px;color:var(--muted);margin-top:8px">worst-case objective '+w.worst_case_score.toFixed(1)+'</div>':'NO VALID POLICY';
}
async function run(){const b=$("#run");b.disabled=true;b.textContent="RUNNING…";try{render(await (await fetch("/api/demo?"+query())).json())}catch(e){$("#guardian").textContent="ENGINE ERROR"}finally{b.disabled=false;b.textContent="RUN EXPERIMENT ↗"}}
["crowd","smoke","capacity"].forEach(id=>$("#"+id).oninput=()=>$("#"+id+"Out").value=$("#"+id).value);
$("#run").onclick=run;run();